stages:
- build
- deploy

build_development:
  image: docker:latest
  stage: build
  environment: development
  only:
    - main
    - feature/cicd
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $DEFAULT_REGISTRY_USERNAME -p $DEFAULT_REGISTRY_ACCESS_TOKEN $CI_REGISTRY
    - echo "$DEVELOPMENT_ENVIRONMENT" > config.json
    - echo "$DEVELOPMENT_ENVIRONMENT" > config.dev.json
    - docker build -t $CI_REGISTRY/tugure/blips/backend/v2/blips-v2-backend/blips-backend:latest . --target production
    - docker push $CI_REGISTRY/tugure/blips/backend/v2/blips-v2-backend/blips-backend:latest

deploy_development:
  image: alpine:3.16.0
  stage: deploy
  environment: development
  only:
    - main
    - feature/cicd
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEVELOPMENT_SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh ubuntu@$DEVELOPMENT_SERVER_IP "bash /home/ubuntu/tugure-builds/modules/blips-backend/update-and-deploy-container.sh"
