version: '3'
services:
  blips-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: blips-backend
    container_name: blips-backend
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    networks:
      - blips-network

#Docker Networks
networks:
  blips-network:
    driver: bridge