definitions:
  dto.ReqAuthUser:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  dto.ReqResetPassword:
    properties:
      password:
        maxLength: 25
        minLength: 8
        type: string
      password_confirmation:
        type: string
    required:
    - password
    - password_confirmation
    type: object
  dto.ReqResetPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  dto.ReqUpdatePassword:
    properties:
      new_password:
        type: string
      old_password:
        type: string
      password_confirmation:
        type: string
    required:
    - new_password
    - old_password
    - password_confirmation
    type: object
  dto.ReqUpdateProfile:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  dto.UserProfile:
    properties:
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      role:
        $ref: '#/definitions/utils.NullString'
      status:
        type: string
      user_id:
        type: string
    type: object
  http.GeneralResponse:
    properties:
      message:
        type: string
    type: object
  http.ResponseAuth:
    properties:
      access_token:
        type: string
    type: object
  utils.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
info:
  contact: {}
  description: Welcome to the API documentation for the Base Template Web Application.
    This comprehensive guide is designed to help developers seamlessly integrate and
    interact with our platform's functionalities. Whether you're building new features,
    enhancing existing ones, or troubleshooting, this documentation provides all the
    necessary resources and information.
  title: Base Template API Documentation
  version: 0.0-beta
paths:
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Sends a password reset email to the provided email address
      parameters:
      - description: Reset Password Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReqResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully Send Reset Email Request
          schema:
            allOf:
            - $ref: '#/definitions/http.GeneralResponse'
            - properties:
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.GeneralResponse'
            - properties:
                message:
                  type: string
              type: object
      summary: Request a password reset email
      tags:
      - Authentication
  /auth/reset-password/{token}:
    post:
      consumes:
      - application/json
      description: Resets the user password using a valid token
      parameters:
      - description: Password Reset Token
        in: path
        name: token
        required: true
        type: string
      - description: Reset User Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReqResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully Reset Password
          schema:
            allOf:
            - $ref: '#/definitions/http.GeneralResponse'
            - properties:
                message:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/http.GeneralResponse'
            - properties:
                message:
                  type: string
              type: object
      summary: Reset user password
      tags:
      - Authentication
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns an access token
      parameters:
      - description: User login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReqAuthUser'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated
          schema:
            $ref: '#/definitions/http.ResponseAuth'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "419":
          description: User password expired
          schema:
            $ref: '#/definitions/http.GeneralResponse'
      summary: Authenticate user
      tags:
      - Authentication
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out the user by invalidating the session token
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "400":
          description: Logout failed
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.GeneralResponse'
      security:
      - BearerAuth: []
      summary: Sign out user
      tags:
      - Authentication
  /v1/auth/password:
    put:
      consumes:
      - application/json
      description: Updates the password of the authenticated user
      parameters:
      - description: New password data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReqUpdatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated password
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.GeneralResponse'
      security:
      - BearerAuth: []
      summary: Update user password
      tags:
      - Authentication
  /v1/auth/profile:
    get:
      consumes:
      - application/json
      description: Retrieves the profile of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: User profile data
          schema:
            $ref: '#/definitions/dto.UserProfile'
        "400":
          description: Failed to get profile
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.GeneralResponse'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - Authentication
    put:
      consumes:
      - application/json
      description: Updates the profile information of the authenticated user
      parameters:
      - description: Updated user profile data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReqUpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated profile
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/http.GeneralResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.GeneralResponse'
      security:
      - BearerAuth: []
      summary: Update user profile
      tags:
      - Authentication
  /v1/auth/refresh-token:
    get:
      consumes:
      - application/json
      description: Generates a new access token based on the provided bearer token.
        If the token is revoked, returns an error.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully refreshed token
          schema:
            $ref: '#/definitions/http.ResponseAuth'
        "400":
          description: Token is revoked or invalid request
          schema:
            allOf:
            - $ref: '#/definitions/http.GeneralResponse'
            - properties:
                message:
                  type: string
              type: object
        "401":
          description: Unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/http.GeneralResponse'
            - properties:
                message:
                  type: string
              type: object
      security:
      - BearerAuth: []
      summary: Refresh access token
      tags:
      - Authentication
securityDefinitions:
  BearerAuth:
    description: 'Enter JWT token (ex: Bearer eyJhbGciOiJIU....)'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
